# Create data

In [1]:
import numpy as np
import pandas as pd

# ============================================================
# 1) INPUT DATA
# ============================================================
movies_to_principals = {
    "Inception (2010)": ["Christopher Nolan","Leonardo DiCaprio","Joseph Gordon-Levitt","Marion Cotillard","Tom Hardy","Hans Zimmer","Wally Pfister","Lee Smith"],
    "Interstellar (2014)": ["Christopher Nolan","Matthew McConaughey","Anne Hathaway","Jessica Chastain","Michael Caine","Hans Zimmer","Hoyte van Hoytema","Lee Smith"],
    "The Dark Knight (2008)": ["Christopher Nolan","Christian Bale","Heath Ledger","Aaron Eckhart","Gary Oldman","Hans Zimmer","Wally Pfister","Lee Smith"],
    "The Dark Knight Rises (2012)": ["Christopher Nolan","Christian Bale","Tom Hardy","Anne Hathaway","Gary Oldman","Hans Zimmer","Wally Pfister","Lee Smith"],
    "Memento (2000)": ["Christopher Nolan","Guy Pearce","Carrie-Anne Moss","Joe Pantoliano","David Julyan","Wally Pfister","Dody Dorn"],
    "Tenet (2020)": ["Christopher Nolan","John David Washington","Robert Pattinson","Elizabeth Debicki","Kenneth Branagh","Ludwig Göransson","Hoyte van Hoytema","Jennifer Lame"],
    "Dunkirk (2017)": ["Christopher Nolan","Fionn Whitehead","Tom Hardy","Mark Rylance","Kenneth Branagh","Hans Zimmer","Hoyte van Hoytema","Lee Smith"],
    "The Prestige (2006)": ["Christopher Nolan","Hugh Jackman","Christian Bale","Scarlett Johansson","Michael Caine","David Julyan","Wally Pfister","Lee Smith"],
    "Oppenheimer (2023)": ["Christopher Nolan","Cillian Murphy","Emily Blunt","Robert Downey Jr.","Matt Damon","Ludwig Göransson","Hoyte van Hoytema","Jennifer Lame"],

    "Pulp Fiction (1994)": ["Quentin Tarantino","John Travolta","Samuel L. Jackson","Uma Thurman","Bruce Willis","Sally Menke","Andrzej Sekula"],
    "Reservoir Dogs (1992)": ["Quentin Tarantino","Harvey Keitel","Tim Roth","Michael Madsen","Steve Buscemi","Sally Menke","Andrzej Sekula"],
    "Kill Bill: Vol. 1 (2003)": ["Quentin Tarantino","Uma Thurman","Lucy Liu","Vivica A. Fox","David Carradine","RZA","Robert Richardson","Sally Menke"],
    "Kill Bill: Vol. 2 (2004)": ["Quentin Tarantino","Uma Thurman","David Carradine","Michael Madsen","Daryl Hannah","RZA","Robert Richardson","Sally Menke"],
    "Inglourious Basterds (2009)": ["Quentin Tarantino","Brad Pitt","Christoph Waltz","Michael Fassbender","Diane Kruger","Ennio Morricone","Robert Richardson","Sally Menke"],
    "Django Unchained (2012)": ["Quentin Tarantino","Jamie Foxx","Christoph Waltz","Leonardo DiCaprio","Samuel L. Jackson","Ennio Morricone","Robert Richardson","Fred Raskin"],
    "The Hateful Eight (2015)": ["Quentin Tarantino","Samuel L. Jackson","Kurt Russell","Jennifer Jason Leigh","Walton Goggins","Ennio Morricone","Robert Richardson","Fred Raskin"],
    "Once Upon a Time in Hollywood (2019)": ["Quentin Tarantino","Leonardo DiCaprio","Brad Pitt","Margot Robbie","Al Pacino","Robert Richardson","Fred Raskin"],
    
    "Star Wars: A New Hope (1977)": ["George Lucas","Mark Hamill","Harrison Ford","Carrie Fisher","Alec Guinness","John Williams","Gilbert Taylor","Paul Hirsch"],
    "The Empire Strikes Back (1980)": ["Irvin Kershner","Mark Hamill","Harrison Ford","Carrie Fisher","Billy Dee Williams","John Williams","Peter Suschitzky","Paul Hirsch"],
    "Return of the Jedi (1983)": ["Richard Marquand","Mark Hamill","Harrison Ford","Carrie Fisher","Ian McDiarmid","John Williams","Alan Hume","Sean Barton"],
    "Star Wars: The Force Awakens (2015)": ["J.J. Abrams","Daisy Ridley","John Boyega","Adam Driver","Harrison Ford","John Williams","Dan Mindel","Maryann Brandon"],

    "The Lord of the Rings: The Fellowship of the Ring (2001)": ["Peter Jackson","Elijah Wood","Ian McKellen","Viggo Mortensen","Sean Astin","Howard Shore","Andrew Lesnie","John Gilbert"],
    "The Lord of the Rings: The Two Towers (2002)": ["Peter Jackson","Elijah Wood","Ian McKellen","Viggo Mortensen","Orlando Bloom","Howard Shore","Andrew Lesnie","Michael Horton"],
    "The Lord of the Rings: The Return of the King (2003)": ["Peter Jackson","Elijah Wood","Ian McKellen","Viggo Mortensen","Sean Astin","Howard Shore","Andrew Lesnie","Jamie Selkirk"],
    "The Hobbit: An Unexpected Journey (2012)": ["Peter Jackson","Martin Freeman","Ian McKellen","Richard Armitage","Andy Serkis","Howard Shore","Andrew Lesnie","Jabez Olssen"],
}

# ============================================================
# 2) BASIC STRUCTURES
# ============================================================
movies_joined = {
    movie: "\n".join(sorted(people))
    for movie, people in movies_to_principals.items()
}

df = pd.DataFrame(
    {
        "movie": list(movies_joined.keys()),
        "principals_joined": list(movies_joined.values())
    }
).set_index("movie")

df = df["principals_joined"].str.get_dummies(sep="\n")
movies = df.index.to_list()
n_movies = len(movies)

print("=== Movie x Principal Incidence Matrix ===")
display(df)

=== Movie x Principal Incidence Matrix ===

,Aaron Eckhart,Adam Driver,Al Pacino,Alan Hume,Alec Guinness,Andrew Lesnie,Andrzej Sekula,Andy Serkis,Anne Hathaway,Billy Dee Williams,...,Sean Astin,Sean Barton,Steve Buscemi,Tim Roth,Tom Hardy,Uma Thurman,Viggo Mortensen,Vivica A. Fox,Wally Pfister,Walton Goggins
movie,,,,,,,,,,,,,,,,,,,,,
Inception (2010),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
Interstellar (2014),0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
The Dark Knight (2008),1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
The Dark Knight Rises (2012),0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
Memento (2000),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Tenet (2020),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Dunkirk (2017),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
The Prestige (2006),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Oppenheimer (2023),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pulp Fiction (1994),0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Reservoir Dogs (1992),0,0,0,0,0,0,1,0,0,0,...,0,0,1,1,0,0,0,0,0,0
Kill Bill: Vol. 1 (2003),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
Kill Bill: Vol. 2 (2004),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Inglourious Basterds (2009),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Django Unchained (2012),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Hateful Eight (2015),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Once Upon a Time in Hollywood (2019),0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Star Wars: A New Hope (1977),0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Empire Strikes Back (1980),0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Return of the Jedi (1983),0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Star Wars: The Force Awakens (2015),0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Lord of the Rings: The Fellowship of the Ring (2001),0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
The Lord of the Rings: The Two Towers (2002),0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
The Lord of the Rings: The Return of the King (2003),0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
The Hobbit: An Unexpected Journey (2012),0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

# Calculate movie similarities

In [7]:
# ============================================================
# 3) JACCARD UTILITIES AND MATRIX
# ============================================================
def jaccard(a: set, b: set) -> float:
    union = a | b
    return len(a & b) / len(union) if union else 0.0

people_sets = {movie: set(people) for movie, people in movies_to_principals.items()}

jacc_mat = np.zeros((n_movies, n_movies), dtype=np.float32)

for i, movie_i in enumerate(movies):
    set_i = people_sets[movie_i]
    for j, movie_j in enumerate(movies):
        if j < i:
            jacc_mat[i, j] = jacc_mat[j, i]
        else:
            set_j = people_sets[movie_j]
            jacc_mat[i, j] = jaccard(set_i, set_j)

df_jacc = pd.DataFrame(jacc_mat, index=movies, columns=movies)

print("=== Jaccard (IoU) Matrix ===")
display(df_jacc)

# ============================================================
# 4) BUILD PAIR DF EARLY
# ============================================================
triu = np.triu_indices(n_movies, k=1)

df_pairs = pd.DataFrame({
    "movie_a": [movies[i] for i in triu[0]],
    "movie_b": [movies[j] for j in triu[1]],
    "jaccard_overlap": jacc_mat[triu].astype(float),
})

print("=== Pair DF (initial) ===")
display(
    df_pairs.sort_values(
        ["jaccard_overlap", "movie_a", "movie_b"],
        ascending=[False, True, True]
    ).reset_index(drop=True).head(25)
)

=== Jaccard (IoU) Matrix ===

,Inception (2010),Interstellar (2014),The Dark Knight (2008),The Dark Knight Rises (2012),Memento (2000),Tenet (2020),Dunkirk (2017),The Prestige (2006),Oppenheimer (2023),Pulp Fiction (1994),...,The Hateful Eight (2015),Once Upon a Time in Hollywood (2019),Star Wars: A New Hope (1977),The Empire Strikes Back (1980),Return of the Jedi (1983),Star Wars: The Force Awakens (2015),The Lord of the Rings: The Fellowship of the Ring (2001),The Lord of the Rings: The Two Towers (2002),The Lord of the Rings: The Return of the King (2003),The Hobbit: An Unexpected Journey (2012)
Inception (2010),1.000000,0.230769,0.333333,0.454545,0.153846,0.066667,0.333333,0.230769,0.066667,0.000000,...,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Interstellar (2014),0.230769,1.000000,0.230769,0.333333,0.071429,0.142857,0.333333,0.230769,0.142857,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
The Dark Knight (2008),0.333333,0.230769,1.000000,0.600000,0.153846,0.066667,0.230769,0.333333,0.066667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
The Dark Knight Rises (2012),0.454545,0.333333,0.600000,1.000000,0.153846,0.066667,0.333333,0.333333,0.066667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Memento (2000),0.153846,0.071429,0.153846,0.153846,1.000000,0.071429,0.071429,0.250000,0.071429,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Tenet (2020),0.066667,0.142857,0.066667,0.066667,0.071429,1.000000,0.230769,0.066667,0.333333,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Dunkirk (2017),0.333333,0.333333,0.230769,0.333333,0.071429,0.230769,1.000000,0.142857,0.142857,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
The Prestige (2006),0.230769,0.230769,0.333333,0.333333,0.250000,0.066667,0.142857,1.000000,0.066667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Oppenheimer (2023),0.066667,0.142857,0.066667,0.066667,0.071429,0.333333,0.142857,0.066667,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Pulp Fiction (1994),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.153846,0.076923,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Reservoir Dogs (1992),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.272727,...,0.071429,0.076923,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Kill Bill: Vol. 1 (2003),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,...,0.142857,0.153846,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Kill Bill: Vol. 2 (2004),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,...,0.142857,0.153846,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Inglourious Basterds (2009),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153846,...,0.230769,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Django Unchained (2012),0.066667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153846,...,0.454545,0.363636,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
The Hateful Eight (2015),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153846,...,1.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Once Upon a Time in Hollywood (2019),0.071429,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.076923,...,0.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Star Wars: A New Hope (1977),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.454545,0.333333,0.142857,0.000000,0.000000,0.000000,0.000000
The Empire Strikes Back (1980),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.454545,1.000000,0.333333,0.142857,0.000000,0.000000,0.000000,0.000000
Return of the Jedi (1983),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.333333,0.333333,1.000000,0.142857,0.000000,0.000000,0.000000,0.000000
Star Wars: The Force Awakens (2015),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.142857,0.142857,0.142857,1.000000,0.000000,0.000000,0.000000,0.000000
The Lord of the Rings: The Fellowship of the Ring (2001),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.600000,0.777778,0.333333
The Lord of the Rings: The Two Towers (2002),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.600000,1.000000,0.600000,0.333333
The Lord of the Rings: The Return of the King (2003),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.777778,0.600000,1.000000,0.333333
The Hobbit: An Unexpected Journey (2012),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.333333,0.333333,1.000000

=== Pair DF (initial) ===

,movie_a,movie_b,jaccard_overlap
0,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Return of the King ...,0.777778
1,Kill Bill: Vol. 1 (2003),Kill Bill: Vol. 2 (2004),0.600000
2,The Dark Knight (2008),The Dark Knight Rises (2012),0.600000
3,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Two Towers (2002),0.600000
4,The Lord of the Rings: The Two Towers (2002),The Lord of the Rings: The Return of the King ...,0.600000
5,Django Unchained (2012),The Hateful Eight (2015),0.454545
6,Inception (2010),The Dark Knight Rises (2012),0.454545
7,Star Wars: A New Hope (1977),The Empire Strikes Back (1980),0.454545
8,Django Unchained (2012),Once Upon a Time in Hollywood (2019),0.363636
9,Inception (2010),Dunkirk (2017),0.333333
10,Inception (2010),The Dark Knight (2008),0.333333
11,Inglourious Basterds (2009),Django Unchained (2012),0.333333
12,Interstellar (2014),Dunkirk (2017),0.333333
13,Interstellar (2014),The Dark Knight Rises (2012),0.333333
14,Star Wars: A New Hope (1977),Return of the Jedi (1983),0.333333
15,Tenet (2020),Oppenheimer (2023),0.333333
16,The Dark Knight (2008),The Prestige (2006),0.333333
17,The Dark Knight Rises (2012),Dunkirk (2017),0.333333
18,The Dark Knight Rises (2012),The Prestige (2006),0.333333
19,The Empire Strikes Back (1980),Return of the Jedi (1983),0.333333
20,The Lord of the Rings: The Fellowship of the R...,The Hobbit: An Unexpected Journey (2012),0.333333
21,The Lord of the Rings: The Return of the King ...,The Hobbit: An Unexpected Journey (2012),0.333333
22,The Lord of the Rings: The Two Towers (2002),The Hobbit: An Unexpected Journey (2012),0.333333
23,Pulp Fiction (1994),Reservoir Dogs (1992),0.272727
24,Inglourious Basterds (2009),Once Upon a Time in Hollywood (2019),0.250000

# SVD embeddings

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

# ============================================================
# 5) SHARED EMBEDDING DIMENSION
# ============================================================
n_components = 10

# ============================================================
# 6) SVD MOVIE EMBEDDINGS
# ============================================================
X = df.values.astype(float)
U, S, Vt = np.linalg.svd(X, full_matrices=False)

df_svd = pd.DataFrame(
    U[:, :n_components] * S[:n_components],
    index=df.index,
    columns=[f"svd_{i+1}" for i in range(n_components)]
)

print("=== SVD Movie Embeddings ===")
display(df_svd)
print()

df_svd_cosine = pd.DataFrame(
    cosine_similarity(df_svd.values),
    index=df.index,
    columns=df.index
)

print("=== SVD cosine similarities for Inception ===")
display(df_svd_cosine.loc["Inception (2010)"].sort_values(ascending=False))

=== SVD Movie Embeddings ===

,svd_1,svd_2,svd_3,svd_4,svd_5,svd_6,svd_7,svd_8,svd_9,svd_10
movie,,,,,,,,,,
Inception (2010),-2.085164e+00,-2.113013e-02,3.877457e-16,-6.069500e-16,6.195808e-01,-1.594123e-01,4.774885e-01,4.170158e-15,-1.072272e-01,-1.169178e+00
Interstellar (2014),-1.921624e+00,-1.766482e-01,-3.978780e-17,3.970701e-16,-3.681635e-01,-1.122789e-02,7.428951e-01,-4.464296e-15,7.336409e-02,1.135368e+00
The Dark Knight (2008),-2.156000e+00,-1.917953e-01,6.739705e-16,4.030497e-16,7.973213e-01,2.936394e-01,-7.896484e-02,1.783311e-15,3.153849e-02,1.794898e-01
The Dark Knight Rises (2012),-2.374714e+00,-2.072722e-01,7.711245e-16,-4.881111e-16,7.567185e-01,2.593058e-01,3.370343e-01,4.070413e-16,2.570066e-02,5.707813e-02
Memento (2000),-1.109866e+00,-1.000058e-01,8.507881e-16,-8.248732e-16,2.450565e-01,1.312582e-01,-1.873852e+00,1.820791e-17,-5.326317e-02,-6.275320e-01
Tenet (2020),-1.097216e+00,-1.090342e-01,-2.661294e-15,1.432417e-16,-2.091669e+00,-4.811573e-01,-2.927357e-01,6.853016e-16,-1.471590e-02,-2.131785e-01
Dunkirk (2017),-1.974103e+00,-1.749042e-01,-9.911866e-16,7.186384e-16,-6.434093e-01,-1.413324e-01,1.127876e+00,-2.368351e-15,8.588258e-03,-3.833293e-01
The Prestige (2006),-1.852248e+00,-1.686716e-01,9.346033e-16,5.114945e-16,6.347262e-01,2.814177e-01,-1.218453e+00,-2.475758e-15,2.895184e-02,7.554857e-01
Oppenheimer (2023),-1.019329e+00,-1.011128e-01,-2.212426e-15,-5.903471e-16,-2.007611e+00,-4.612134e-01,-6.021781e-01,2.606036e-15,-1.840265e-02,5.913395e-02
Pulp Fiction (1994),-1.100023e-01,1.526856e+00,4.168665e-17,-2.062352e-17,-2.218096e-01,8.465909e-01,5.548319e-03,-5.230931e-14,1.264993e+00,1.562005e-01
Reservoir Dogs (1992),-8.872151e-02,1.263679e+00,1.034454e-15,8.207214e-16,-2.655169e-01,1.064743e+00,3.500104e-02,-6.334839e-14,1.527720e+00,-5.641112e-01
Kill Bill: Vol. 1 (2003),-1.442435e-01,2.001018e+00,1.814163e-15,-3.447053e-17,-3.147261e-01,1.232704e+00,4.503471e-02,4.802798e-14,-1.158476e+00,1.889692e-01
Kill Bill: Vol. 2 (2004),-1.474880e-01,2.053497e+00,1.471801e-15,-1.872140e-16,-3.422286e-01,1.349883e+00,5.123521e-02,3.310126e-14,-8.056125e-01,2.342814e-02
Inglourious Basterds (2009),-1.565717e-01,1.986303e+00,-1.240889e-15,-6.497301e-16,7.181234e-02,-4.436880e-01,-6.564636e-02,3.996634e-15,-8.956551e-02,-6.634365e-02
Django Unchained (2012),-2.441593e-01,1.981870e+00,-1.768451e-15,-4.278562e-16,3.815031e-01,-1.490776e+00,-2.692658e-02,-7.255518e-15,1.756675e-01,8.291057e-03
The Hateful Eight (2015),-1.509735e-01,1.828033e+00,-1.236499e-15,1.063040e-15,2.677719e-01,-1.287867e+00,-1.254594e-01,-1.586079e-14,3.707871e-01,8.167097e-01
Once Upon a Time in Hollywood (2019),-2.133125e-01,1.585375e+00,-1.669542e-15,-1.624378e-16,2.928709e-01,-1.037724e+00,4.582972e-02,1.900601e-14,-4.528571e-01,-7.108933e-01
Star Wars: A New Hope (1977),9.233301e-19,-3.578433e-16,-3.083925e-15,2.360607e+00,-2.964123e-17,9.546240e-17,1.745680e-16,-5.601549e-01,-2.166909e-14,-5.016485e-16
The Empire Strikes Back (1980),-5.934027e-19,-9.714446e-17,-6.511715e-16,2.360607e+00,-4.966153e-17,-1.676536e-16,8.823654e-17,-5.601549e-01,-2.233755e-14,-1.158204e-16
Return of the Jedi (1983),-4.410007e-19,-7.384875e-18,-6.431275e-16,2.190726e+00,1.685692e-17,-7.254170e-17,2.139401e-17,-3.597681e-01,-1.385062e-14,-2.926700e-16
Star Wars: The Force Awakens (2015),-7.761873e-18,3.187270e-17,-2.862605e-16,1.396958e+00,-2.663122e-17,-2.613785e-17,-4.531643e-16,2.457313e+00,9.469485e-14,-1.885829e-16
The Lord of the Rings: The Fellowship of the Ring (2001),-2.147034e-19,9.210426e-17,2.613344e+00,8.256244e-16,-1.083171e-15,-1.382357e-15,4.297501e-16,-2.018278e-16,2.671216e-16,2.206507e-17
The Lord of the Rings: The Two Towers (2002),-2.071441e-19,8.837811e-17,2.493073e+00,5.895781e-16,-1.031584e-15,-1.311622e-15,4.020518e-16,-3.911567e-17,1.533580e-16,2.839883e-17
The Lord of the Rings: The Return of the King (2003),-2.147034e-19,9.210426e-17,2.613344e+00,8.256244e-16,-1.083171e-15,-1.382357e-15,4.297501e-16,8.758434e-17,2.671216e-16,2.206495e-17
The Hobbit: An Unexpected Journey (2012),-1.791983e-19,7.321497e-17,1.963219e+00,5.368119e-16,-8.220390e-16,-1.120788e-15,1.719850e-16,1.659736e-17,1.814655e-16,-3.412522e-16

=== SVD cosine similarities for Inception ===

movie
Inception (2010)                                            1.000000e+00
The Dark Knight Rises (2012)                                8.552350e-01
The Dark Knight (2008)                                      7.976130e-01
Dunkirk (2017)                                              7.797838e-01
Interstellar (2014)                                         4.652716e-01
The Prestige (2006)                                         4.444726e-01
Memento (2000)                                              3.973802e-01
Once Upon a Time in Hollywood (2019)                        3.124479e-01
Tenet (2020)                                                1.920180e-01
Django Unchained (2012)                                     1.411432e-01
Oppenheimer (2023)                                          1.004057e-01
Inglourious Basterds (2009)                                 8.823373e-02
Reservoir Dogs (1992)                                       5.707279e-02
The Hobbit: An Unexpected Journey (2012)                    1.799140e-16
The Lord of the Rings: The Return of the King (2003)        1.079714e-16
The Lord of the Rings: The Fellowship of the Ring (2001)    1.079714e-16
The Lord of the Rings: The Two Towers (2002)                1.077237e-16
Star Wars: The Force Awakens (2015)                        -1.047673e-16
Star Wars: A New Hope (1977)                               -1.312414e-16
Return of the Jedi (1983)                                  -1.730712e-16
The Empire Strikes Back (1980)                             -1.955258e-16
Kill Bill: Vol. 2 (2004)                                   -1.207706e-02
Kill Bill: Vol. 1 (2003)                                   -3.114635e-02
The Hateful Eight (2015)                                   -6.636114e-02
Pulp Fiction (1994)                                        -7.121621e-02
Name: Inception (2010), dtype: float64

# Spectral embeddings

In [5]:
from sklearn.manifold import SpectralEmbedding

# ============================================================
# 7) SPECTRAL EMBEDDING FROM JACCARD AFFINITY
# ============================================================
df_jacc_affinity = jacc_mat.copy()
np.fill_diagonal(df_jacc_affinity, 1.0)

arr_spectral_jacc = SpectralEmbedding(
    n_components=n_components,
    affinity="precomputed",
    random_state=42
).fit_transform(df_jacc_affinity)

df_spectral_jacc = pd.DataFrame(
    arr_spectral_jacc,
    index=movies,
    columns=[f"spec_jacc_{i+1}" for i in range(n_components)]
)

print("=== Spectral Embedding from Jaccard Affinity ===")
display(df_spectral_jacc)
print()

df_spectral_jacc_cosine = pd.DataFrame(
    cosine_similarity(df_spectral_jacc.values),
    index=df_spectral_jacc.index,
    columns=df.spectral_jacc.index if False else df_spectral_jacc.index
)

print("=== Spectral-Jaccard cosine similarities for Inception ===")
display(df_spectral_jacc_cosine.loc["Inception (2010)"].sort_values(ascending=False))

=== Spectral Embedding from Jaccard Affinity ===

C:\Users\Graham West\anaconda3\envs\havi\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(

,spec_jacc_1,spec_jacc_2,spec_jacc_3,spec_jacc_4,spec_jacc_5,spec_jacc_6,spec_jacc_7,spec_jacc_8,spec_jacc_9,spec_jacc_10
Inception (2010),-0.016195,0.039257,-1.557000e-01,-1.450265e-01,9.918988e-03,-1.330623e-01,-1.476200e-02,-4.200159e-01,-1.466267e-01,-8.647971e-02
Interstellar (2014),-0.016195,0.039257,-1.794000e-01,4.267877e-02,-1.132720e-03,-2.187850e-01,1.026031e-02,4.556784e-01,-2.923031e-01,8.484652e-02
The Dark Knight (2008),-0.016195,0.039257,-1.784385e-01,-1.903304e-01,-5.999514e-02,-9.555312e-03,6.138057e-03,3.214711e-02,4.116334e-01,3.802456e-02
The Dark Knight Rises (2012),-0.016195,0.039257,-1.779106e-01,-1.786166e-01,-5.312549e-02,-1.120987e-01,5.631494e-03,-2.276985e-03,2.307172e-01,1.188184e-02
Memento (2000),-0.016195,0.039257,-1.789980e-01,-8.619455e-02,-3.826072e-02,6.800936e-01,-1.216714e-02,-1.859849e-01,-3.228251e-01,-8.303367e-02
Tenet (2020),-0.016195,0.039257,-1.817182e-01,5.816171e-01,1.313182e-01,7.924505e-02,-2.820970e-03,-7.873820e-02,1.464452e-01,-3.349983e-03
Dunkirk (2017),-0.016195,0.039257,-1.785279e-01,9.974372e-02,2.075540e-02,-3.080398e-01,4.035466e-03,-8.213384e-02,-2.612116e-01,-7.024226e-02
The Prestige (2006),-0.016195,0.039257,-1.790931e-01,-1.586915e-01,-5.734489e-02,3.370464e-01,8.270222e-04,2.533344e-01,-1.069927e-01,5.692598e-02
Oppenheimer (2023),-0.016195,0.039257,-1.816974e-01,5.914210e-01,1.333344e-01,1.536435e-01,-3.943576e-03,-4.285315e-02,2.435781e-01,2.743075e-02
Pulp Fiction (1994),-0.016195,0.039256,2.201250e-01,5.921454e-02,-2.417773e-01,-1.356142e-04,4.458831e-01,1.649107e-02,8.398277e-03,-2.406518e-01
Reservoir Dogs (1992),-0.016195,0.039256,2.207263e-01,7.725565e-02,-3.258699e-01,-6.016360e-03,5.400507e-01,-1.225661e-01,-4.624037e-02,2.488761e-01
Kill Bill: Vol. 1 (2003),-0.016195,0.039256,2.200307e-01,6.269541e-02,-2.614225e-01,-9.195278e-03,-3.835296e-01,3.068102e-02,1.207933e-02,-1.197813e-01
Kill Bill: Vol. 2 (2004),-0.016195,0.039256,2.202335e-01,6.781968e-02,-2.848310e-01,-1.002069e-02,-2.920996e-01,1.820999e-03,1.083329e-03,-5.717163e-02
Inglourious Basterds (2009),-0.016195,0.039256,2.165144e-01,-2.074853e-02,1.192116e-01,1.351604e-02,-1.948358e-02,3.237385e-02,7.651304e-03,5.360450e-01
Django Unchained (2012),-0.016195,0.039256,2.028848e-01,-8.045186e-02,3.441921e-01,7.929360e-03,4.606115e-02,2.718659e-02,1.084422e-02,-1.235325e-01
The Hateful Eight (2015),-0.016195,0.039256,2.145707e-01,-6.460981e-02,3.185092e-01,2.490212e-02,8.481079e-02,1.876063e-01,7.091383e-02,-3.956429e-01
Once Upon a Time in Hollywood (2019),-0.016195,0.039256,1.986274e-01,-7.543664e-02,2.966807e-01,-8.995718e-03,-1.198799e-01,-1.977036e-01,-7.447691e-02,2.221236e-01
Star Wars: A New Hope (1977),0.553870,0.124037,3.348693e-07,2.563021e-08,4.708850e-08,-2.740668e-08,2.335761e-08,7.485950e-08,-1.642601e-06,-7.730261e-06
The Empire Strikes Back (1980),0.553870,0.124037,4.507520e-07,-5.261136e-09,9.266469e-09,1.048252e-07,1.357871e-07,-1.277026e-07,-1.990134e-06,-7.274614e-06
Return of the Jedi (1983),0.553870,0.124037,5.192683e-07,7.989676e-08,2.099949e-09,1.639901e-07,1.133888e-07,-1.358724e-08,-6.017129e-07,-2.576121e-06
Star Wars: The Force Awakens (2015),0.553870,0.124038,5.380023e-07,2.213056e-08,8.775925e-08,2.577969e-07,-5.293180e-07,-4.159288e-07,8.858106e-06,3.751178e-05
The Lord of the Rings: The Fellowship of the Ring (2001),-0.084162,0.391206,5.903178e-07,-2.426636e-08,-1.546358e-08,-3.453056e-07,2.053532e-07,-8.885761e-09,2.124637e-07,-2.050763e-07
The Lord of the Rings: The Two Towers (2002),-0.084162,0.391206,5.429405e-07,9.635307e-09,6.436039e-08,9.216674e-09,8.900154e-08,4.119513e-08,7.221528e-08,7.669614e-11
The Lord of the Rings: The Return of the King (2003),-0.084162,0.391206,5.042666e-07,-6.421235e-09,2.815367e-08,1.645892e-07,-1.410233e-07,-6.157146e-08,1.099408e-07,4.328477e-07
The Hobbit: An Unexpected Journey (2012),-0.084162,0.391206,5.557451e-07,1.202345e-09,8.276770e-08,2.378727e-07,-2.064194e-08,1.215048e-08,-3.979734e-07,-6.258661e-07

=== Spectral-Jaccard cosine similarities for Inception ===

Inception (2010)                                            1.000000
Dunkirk (2017)                                              0.555417
Once Upon a Time in Hollywood (2019)                        0.243494
Memento (2000)                                              0.200424
The Dark Knight Rises (2012)                                0.188004
The Hobbit: An Unexpected Journey (2012)                    0.080341
The Lord of the Rings: The Fellowship of the Ring (2001)    0.080341
The Lord of the Rings: The Two Towers (2002)                0.080341
The Lord of the Rings: The Return of the King (2003)        0.080341
The Empire Strikes Back (1980)                             -0.013887
Star Wars: A New Hope (1977)                               -0.013888
Return of the Jedi (1983)                                  -0.013890
Star Wars: The Force Awakens (2015)                        -0.013906
Reservoir Dogs (1992)                                      -0.045897
The Dark Knight (2008)                                     -0.075172
Django Unchained (2012)                                    -0.083613
Pulp Fiction (1994)                                        -0.118229
Kill Bill: Vol. 2 (2004)                                   -0.143913
Kill Bill: Vol. 1 (2003)                                   -0.149638
Tenet (2020)                                               -0.152211
The Hateful Eight (2015)                                   -0.252640
Oppenheimer (2023)                                         -0.261033
Inglourious Basterds (2009)                                -0.292516
Interstellar (2014)                                        -0.320726
The Prestige (2006)                                        -0.336585
Name: Inception (2010), dtype: float32

# Comparing performance

In [6]:
# ============================================================
# 8) FINAL PAIR TABLE WITH ALL SIMILARITIES
# ============================================================

# append pairwise SVD cosine to df_pairs
df_pairs["svd_cosine"] = [
    df_svd_cosine.loc[movie_a, movie_b]
    for movie_a, movie_b in zip(df_pairs["movie_a"], df_pairs["movie_b"])
]

# append pairwise spectral cosine to df_pairs
df_pairs["spectral_jacc_cosine"] = [
    df_spectral_jacc_cosine.loc[movie_a, movie_b]
    for movie_a, movie_b in zip(df_pairs["movie_a"], df_pairs["movie_b"])
]

df_pairs = df_pairs.sort_values(
    ["jaccard_overlap", "svd_cosine", "spectral_jacc_cosine", "movie_a", "movie_b"],
    ascending=[False, False, False, True, True]
).reset_index(drop=True)

print("=== Pair DF with Jaccard + SVD cosine + Spectral-Jaccard cosine ===")
display(df_pairs)

print("=== Top pairs with nonzero Jaccard overlap ===")
display(df_pairs.loc[df_pairs["jaccard_overlap"] > 0].head(25))

=== Pair DF with Jaccard + SVD cosine + Spectral-Jaccard cosine ===

,movie_a,movie_b,jaccard_overlap,svd_cosine,spectral_jacc_cosine
0,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Return of the King ...,0.777778,1.000000,1.000000
1,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Two Towers (2002),0.600000,1.000000,1.000000
2,The Lord of the Rings: The Two Towers (2002),The Lord of the Rings: The Return of the King ...,0.600000,1.000000,1.000000
3,Kill Bill: Vol. 1 (2003),Kill Bill: Vol. 2 (2004),0.600000,0.987882,0.979810
4,The Dark Knight (2008),The Dark Knight Rises (2012),0.600000,0.983333,0.921207
...,...,...,...,...,...
295,Memento (2000),The Hateful Eight (2015),0.000000,-0.074787,-0.108218
296,Dunkirk (2017),The Hateful Eight (2015),0.000000,-0.079239,-0.177924
297,Interstellar (2014),Reservoir Dogs (1992),0.000000,-0.084068,-0.107125
298,The Prestige (2006),Once Upon a Time in Hollywood (2019),0.000000,-0.113336,-0.286762
299,Interstellar (2014),Once Upon a Time in Hollywood (2019),0.000000,-0.153604,-0.281679

=== Top pairs with nonzero Jaccard overlap ===

,movie_a,movie_b,jaccard_overlap,svd_cosine,spectral_jacc_cosine
0,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Return of the King ...,0.777778,1.000000,1.000000
1,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Two Towers (2002),0.600000,1.000000,1.000000
2,The Lord of the Rings: The Two Towers (2002),The Lord of the Rings: The Return of the King ...,0.600000,1.000000,1.000000
3,Kill Bill: Vol. 1 (2003),Kill Bill: Vol. 2 (2004),0.600000,0.987882,0.979810
4,The Dark Knight (2008),The Dark Knight Rises (2012),0.600000,0.983333,0.921207
5,Star Wars: A New Hope (1977),The Empire Strikes Back (1980),0.454545,1.000000,1.000000
6,Django Unchained (2012),The Hateful Eight (2015),0.454545,0.936654,0.848208
7,Inception (2010),The Dark Knight Rises (2012),0.454545,0.855235,0.188004
8,Django Unchained (2012),Once Upon a Time in Hollywood (2019),0.363636,0.895603,0.521734
9,The Lord of the Rings: The Fellowship of the R...,The Hobbit: An Unexpected Journey (2012),0.333333,1.000000,1.000000
10,The Lord of the Rings: The Return of the King ...,The Hobbit: An Unexpected Journey (2012),0.333333,1.000000,1.000000
11,The Lord of the Rings: The Two Towers (2002),The Hobbit: An Unexpected Journey (2012),0.333333,1.000000,1.000000
12,Star Wars: A New Hope (1977),Return of the Jedi (1983),0.333333,0.997536,1.000000
13,The Empire Strikes Back (1980),Return of the Jedi (1983),0.333333,0.997536,1.000000
14,Tenet (2020),Oppenheimer (2023),0.333333,0.984514,0.983423
15,Inglourious Basterds (2009),Django Unchained (2012),0.333333,0.898847,0.087396
16,The Dark Knight (2008),The Prestige (2006),0.333333,0.848101,0.121763
17,Inception (2010),The Dark Knight (2008),0.333333,0.797613,-0.075172
18,Inception (2010),Dunkirk (2017),0.333333,0.779784,0.555417
19,Interstellar (2014),Dunkirk (2017),0.333333,0.777645,0.477584
20,Interstellar (2014),The Dark Knight Rises (2012),0.333333,0.764726,-0.073694
21,The Dark Knight Rises (2012),Dunkirk (2017),0.333333,0.747241,-0.068356
22,The Dark Knight Rises (2012),The Prestige (2006),0.333333,0.743405,0.014571
23,Pulp Fiction (1994),Reservoir Dogs (1992),0.272727,0.932950,0.703502
24,Inglourious Basterds (2009),Once Upon a Time in Hollywood (2019),0.250000,0.869819,0.669491